import { useState, useEffect } from 'react'
import { Link, useNavigate } from 'react-router-dom'

const moonstackLogo = '/moonstack-all-white.webp'
const landingPageImg = '/landing_page_img.webp'

const galleryImages = [
  '/images/better_food_co.webp',
  '/images/bos_coffee.webp',
  '/images/barnana.webp',
  '/images/fox_point_grocers.webp',
  '/images/got_baked.webp',
  '/images/loveshackfancy.webp',
  '/images/MiN_ny.webp',
  '/images/PONTO2.webp',
]

function Home() {
  const [isScrolled, setIsScrolled] = useState(false)
  const [textVisible, setTextVisible] = useState(false)
  const [loadedSrcs, setLoadedSrcs] = useState<Set<string>>(new Set())
  const [websiteUrl, setWebsiteUrl] = useState('')
  const navigate = useNavigate()

  const handleSubmit = async () => {
    const trimmed = websiteUrl.trim()
    if (!trimmed) return

    let submissionId: number | null = null
    try {
      const res = await fetch('http://localhost:8000/submissions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          url: trimmed,
          company_name: 'Basemicrobe',
          company_type: 'Biotech',
          colors: ['Green', 'Gray', 'White'],
          products: ['Psyllium Colon Cleanse', 'Fruit Fizz-C', 'Vegan Leather'],
        }),
      })
      const data = await res.json()
      submissionId = data.id
    } catch {}

    const params = new URLSearchParams({ url: trimmed })
    if (submissionId) params.set('id', String(submissionId))
    navigate(`/create?${params.toString()}`)
  }

  useEffect(() => {
    const handleScroll = () => setIsScrolled(window.scrollY > 50)
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  useEffect(() => {
    // Text fades in on mount
    setTextVisible(true)

    // Preload gallery images — each fades in as it loads
    galleryImages.forEach((src) => {
      const img = new Image()
      img.onload = img.onerror = () => {
        setLoadedSrcs(prev => new Set([...prev, src]))
      }
      img.src = src
    })
  }, [])

  return (
    <div className="app">
      {/* Navigation */}
      <nav className={`navbar ${isScrolled ? 'scrolled' : ''}`}>
        <div className="nav-container">
          <div className="logo">
            <Link to="/">
              <img src={moonstackLogo} alt="Moonstack" className="logo-icon" />
            </Link>
          </div>
          <div className="nav-links">
            <a href="#about">About</a>
            <a href="#features">Features</a>
            {/* <Link to="/blog">Blog</Link> */}
            {/* <a href="#contact">Contact</a> */}
            <a href="https://calendar.app.google/WdqnkAnLUJQvMKcY6" target="_blank" rel="noopener noreferrer" className="btn-primary">Book a Call</a>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section id="hero" className="hero" style={{ backgroundImage: `url(${landingPageImg})`, backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }}>
        <div className="hero-background">
          <div className="gradient-orb orb-1"></div>
          <div className="gradient-orb orb-2"></div>
          <div className="gradient-orb orb-3"></div>
        </div>
        {/* Text fades in on mount */}
        <div className="hero-content" style={{ opacity: textVisible ? 1 : 0, transition: 'opacity 0.7s ease', animation: 'none' }}>
          <h1 className="hero-title">
            Create Visuals that Define <b><b>Your Brand</b></b>
          </h1>
          <p className="hero-description">
            Moonstack crafts designer-quality ads that make your brand impossible to ignore
          </p>
          <div className="hero-cta">
            <a href="https://calendar.app.google/WdqnkAnLUJQvMKcY6" target="_blank" rel="noopener noreferrer" className="btn-primary btn-large">Book a Call</a>
            <a href="https://www.youtube.com/@trymoonstack" target="_blank" rel="noopener noreferrer" className="btn-secondary btn-large">Watch Demo</a>
          </div>
          <div className="hero-input-row">
            <div className="hero-input-pill">
              <input type="text" className="hero-input" placeholder="Put your website link here" value={websiteUrl} onChange={e => setWebsiteUrl(e.target.value)} onKeyDown={e => e.key === 'Enter' && handleSubmit()} />
              <button className="hero-input-submit" onClick={handleSubmit}>Submit</button>
            </div>
          </div>
        </div>
      </section>

      {/* Gallery Marquee Section */}
      <section className="gallery-marquee">
        <p className="gallery-label">Images generated by Moonstack</p>
        <div className="marquee-track">
          {[...galleryImages, ...galleryImages].map((src, i) => (
            <div
              className="marquee-item"
              key={i}
              style={{ opacity: loadedSrcs.has(src) ? 1 : 0, transition: 'opacity 0.6s ease' }}
            >
              <img src={src} alt="" />
            </div>
          ))}
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="about">
        <div className="container">
          <div className="about-content">
            <div className="about-text">
              <h2 className="section-title">Built for the AI era</h2>
              <p className="about-description">
                Remove the guesswork in ad creation.
              </p>
              <p className="about-description">
                Moonstack is the AI-powered marketing agency that helps brands create visuals that reaches their audience and grows their business.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      {/* <section id="features" className="features">
        <div className="container">
          <div className="section-header">
            <h2 className="section-title">Everything your brand needs to stand out</h2>
          </div>
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">🎬</div>
              <h3 className="feature-title">Video Processing</h3>
              <p className="feature-description">
                Automatically processes, stitches, and enhances video scenes with AI-powered tools
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🎙️</div>
              <h3 className="feature-title">Audio Transcription</h3>
              <p className="feature-description">
                Transcribes the video with industry-leading accuracy and multiple language support
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">📝</div>
              <h3 className="feature-title">Smart Captions</h3>
              <p className="feature-description">
                Generates professional, time-synced captions that enhance accessibility and engagement
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🔊</div>
              <h3 className="feature-title">Voice Synthesis</h3>
              <p className="feature-description">
                Creates natural-sounding voiceovers and dubbing in multiple voices and languages
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🎨</div>
              <h3 className="feature-title">Scene Stitching</h3>
              <p className="feature-description">
                Seamlessly combines multiple video scenes with intelligent transitions
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">⚡</div>
              <h3 className="feature-title">Lightning Fast</h3>
              <p className="feature-description">
                Processes large files in minutes, not hours, with our optimized AI pipeline
              </p>
            </div>
          </div>
        </div>
      </section> */}

      {/* CTA Section */}
      <section className="cta">
        <div className="container">
          <div className="cta-content">
            <h2 className="cta-title">Take your brand visuals to the moon</h2>
            <p className="cta-description">
            </p>
            <a href="https://calendar.app.google/WdqnkAnLUJQvMKcY6" target="_blank" rel="noopener noreferrer" className="btn-primary btn-large">Book a Call</a>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-section">
              <div className="logo">
                <img src={moonstackLogo} alt="Moonstack" className="logo-icon" />
                <span className="logo-text">Moonstack</span>
              </div>
              <p className="footer-description">
                Creating visuals that define brands, from startups finding their voice to enterprises redefining theirs.
              </p>
            </div>
            <div className="footer-section">
              <h4 className="footer-title">Product</h4>
              <a href="#features">Features</a>
              <a href="#pricing">Pricing</a>
              <a href="#docs">Documentation</a>
            </div>
            <div className="footer-section">
              <h4 className="footer-title">Company</h4>
              <a href="#about">About</a>
              <a href="#careers">Careers</a>
            </div>
            <div className="footer-section">
              <h4 className="footer-title">Support</h4>
              <a href="#contact">Contact</a>
              <a href="#help">Help Center</a>
              <a href="#status">Status</a>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; 2025 Moonstack. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Home
