import { useState, useEffect } from 'react'
import { Link } from 'react-router-dom'
import moonstackLogo from '../assets/moonstack-all-white.png'
import landingPageImg from '../assets/landing_page_img2.png'

import betterFoodCo from '../assets/images/better_food_co.png'
import bosCoffee from '../assets/images/bos_coffee.png'
import echoLabAd from '../assets/images/echo-lab-ad1-2.png'
import foxPointGrocers from '../assets/images/fox_point_grocers.png'
import gotBaked from '../assets/images/got_baked.png'
import loveshackfancy from '../assets/images/loveshackfancy.png'
import MiNNY from '../assets/images/MiN_ny.png'
import Ponto2 from '../assets/images/PONTO2.png'

const galleryImages = [
  betterFoodCo, bosCoffee, echoLabAd, foxPointGrocers, 
  gotBaked, loveshackfancy, MiNNY, Ponto2
]

function Home() {
  const [isScrolled, setIsScrolled] = useState(false)
  const [imagesLoaded, setImagesLoaded] = useState(false)

  useEffect(() => {
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50)
    }
    window.addEventListener('scroll', handleScroll)
    return () => window.removeEventListener('scroll', handleScroll)
  }, [])

  useEffect(() => {
    let loaded = 0
    const total = galleryImages.length
    galleryImages.forEach((src) => {
      const img = new Image()
      img.onload = img.onerror = () => {
        loaded++
        if (loaded === total) setImagesLoaded(true)
      }
      img.src = src
    })
  }, [])

  return (
    <div className="app">
      {/* Navigation */}
      <nav className={`navbar ${isScrolled ? 'scrolled' : ''}`}>
        <div className="nav-container">
          <div className="logo">
            <Link to="/">
              <img src={moonstackLogo} alt="Moonstack" className="logo-icon" />
            </Link>
          </div>
          <div className="nav-links">
            <a href="#about">About</a>
            <a href="#features">Features</a>
            {/* <Link to="/blog">Blog</Link> */}
            {/* <a href="#contact">Contact</a> */}
            <a href="https://calendar.app.google/WdqnkAnLUJQvMKcY6" target="_blank" rel="noopener noreferrer" className="btn-primary">Book a Call</a>
          </div>
        </div>
      </nav>

      {/* Hero Section */}
      <section id="hero" className="hero" style={{ backgroundImage: `url(${landingPageImg})`, backgroundSize: 'cover', backgroundPosition: 'center', backgroundRepeat: 'no-repeat' }}>
        <div className="hero-background">
          <div className="gradient-orb orb-1"></div>
          <div className="gradient-orb orb-2"></div>
          <div className="gradient-orb orb-3"></div>
        </div>
        <div className="hero-content">
          <h1 className="hero-title">
            Create Visuals that Define <b><b>Your Brand</b></b>
          </h1>
          <p className="hero-description">
            Moonstack crafts distinctive visual identities that make your brand impossible to ignore
          </p>
          <div className="hero-cta">
            <a href="https://calendar.app.google/WdqnkAnLUJQvMKcY6" target="_blank" rel="noopener noreferrer" className="btn-primary btn-large">Book a Call</a>
            <a href="https://www.youtube.com/@trymoonstack" target="_blank" rel="noopener noreferrer" className="btn-secondary btn-large">Watch Demo</a>
          </div>
        </div>
      </section>

      {/* Gallery Marquee Section */}
      <section
        className="gallery-marquee"
        style={{
          opacity: imagesLoaded ? 1 : 0,
          transition: 'opacity 0.8s ease',
        }}
      >
        <p className="gallery-label">generated by Moonstack</p>
        <div className="marquee-track">
          {[...galleryImages, ...galleryImages].map((src, i) => (
            <div className="marquee-item" key={i}>
              <img src={src} alt="" />
            </div>
          ))}
        </div>
      </section>

      {/* About Section */}
      <section id="about" className="about">
        <div className="container">
          <div className="about-content">
            <div className="about-text">
              <h2 className="section-title">Built for the AI era</h2>
              <p className="about-description">
                The best AI video models should be in the hands of everyone, not just those with technical expertise or big budgets.
              </p>
              <p className="about-description">
                At Moonstack, our mission is to democratize access to powerful video generation tools, enabling anyone to create high-quality videos with just a few words.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Features Section */}
      {/* <section id="features" className="features">
        <div className="container">
          <div className="section-header">
            <h2 className="section-title">Everything your brand needs to stand out</h2>
          </div>
          <div className="features-grid">
            <div className="feature-card">
              <div className="feature-icon">🎬</div>
              <h3 className="feature-title">Video Processing</h3>
              <p className="feature-description">
                Automatically processes, stitches, and enhances video scenes with AI-powered tools
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🎙️</div>
              <h3 className="feature-title">Audio Transcription</h3>
              <p className="feature-description">
                Transcribes the video with industry-leading accuracy and multiple language support
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">📝</div>
              <h3 className="feature-title">Smart Captions</h3>
              <p className="feature-description">
                Generates professional, time-synced captions that enhance accessibility and engagement
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🔊</div>
              <h3 className="feature-title">Voice Synthesis</h3>
              <p className="feature-description">
                Creates natural-sounding voiceovers and dubbing in multiple voices and languages
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">🎨</div>
              <h3 className="feature-title">Scene Stitching</h3>
              <p className="feature-description">
                Seamlessly combines multiple video scenes with intelligent transitions
              </p>
            </div>
            <div className="feature-card">
              <div className="feature-icon">⚡</div>
              <h3 className="feature-title">Lightning Fast</h3>
              <p className="feature-description">
                Processes large files in minutes, not hours, with our optimized AI pipeline
              </p>
            </div>
          </div>
        </div>
      </section> */}

      {/* CTA Section */}
      <section className="cta">
        <div className="container">
          <div className="cta-content">
            <h2 className="cta-title">Take your brand visuals to the moon</h2>
            <p className="cta-description">
            </p>
            <a href="https://calendar.app.google/WdqnkAnLUJQvMKcY6" target="_blank" rel="noopener noreferrer" className="btn-primary btn-large">Book a Call</a>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="footer">
        <div className="container">
          <div className="footer-content">
            <div className="footer-section">
              <div className="logo">
                <img src={moonstackLogo} alt="Moonstack" className="logo-icon" />
                <span className="logo-text">Moonstack</span>
              </div>
              <p className="footer-description">
                Creating visuals that define brands, from startups finding their voice to enterprises redefining theirs.
              </p>
            </div>
            <div className="footer-section">
              <h4 className="footer-title">Product</h4>
              <a href="#features">Features</a>
              <a href="#pricing">Pricing</a>
              <a href="#docs">Documentation</a>
            </div>
            <div className="footer-section">
              <h4 className="footer-title">Company</h4>
              <a href="#about">About</a>
              <a href="#careers">Careers</a>
            </div>
            <div className="footer-section">
              <h4 className="footer-title">Support</h4>
              <a href="#contact">Contact</a>
              <a href="#help">Help Center</a>
              <a href="#status">Status</a>
            </div>
          </div>
          <div className="footer-bottom">
            <p>&copy; 2025 Moonstack. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}

export default Home
